apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
        - name: test-server
          image: shestera/scaletestapp:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "30Mi"
